---
# Create a Custom Network
- name: Create Custom Network
  hosts: localhost
  connection: local
  tasks:
    - name: Deploy New Customer Network
      gce_net:
        name: "{{ vpc_name }}"
        mode: "{{ vpc_mode }}"
        subnet_name: "{{ vpc_subnet_name }}"
        subnet_region: "{{ vpc_region }}"
        ipv4_range: '10.240.17.0/24'
        state: "present"
        

## Example:
#- name: Create Custom Network
#  hosts: localhost
#  connection: local
#  tasks:
#    - name: Deploy New Customer Network
#      gce_net:
#        name: customnet
#        mode: custom
#        subnet_name: "customsubnet"
#        subnet_region: us-east1
#        ipv4_range: '10.240.17.0/24'
#        state: "present"
