---
# Create a Custom Network

- name: Create Custom Network
  hosts: localhost
  connection: local
  tasks:
    - name: Deploy New Customer Network
      gce_net:
        name: customnet
        mode: custom
        #subnet_name: "customsubnet"
        subnet_name: {{ tela_name }}
        subnet_region: us-east1
        ipv4_range: '10.240.17.0/24'
        state: "present"
