---
# Create a simple VM

- name: Create a simple Network VM Tag
  hosts: localhost
  connection: local
  tasks:
    - name: Deploy new VM instance
      gce_tag:
        instance_name: leo-1
        tags: staging1
        zone: us-central1-a
        state: present
